apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sapp
  name: spring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sapp
  template:
    metadata:
      labels:
        app: sapp
    spec:
      containers:
       - image: lerndevops/samples:springboot-app
         name: cont1
         envFrom: 
          - configMapRef: 
              name: spring-app-config
