bases:
  - ../../base
namespace: dev
#patches:
#  - replica_count.yaml
#  - resource_limits.yml
#  - devdbconf.yml
configMapGenerator:
  - name: spring-app-xyz-config
    files:
     - configs/app.json
patchesStrategicMerge:
  - env.yml
  - replica_count.yaml
  - resource_limits.yml
  - dbconf.yml
  - namespace.yml
